services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-network

  finance-analyzer-users-microservice:
    build: ./finance-analyzer-users-microservice
    ports:
      - "4000:4000"
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: auth_db
      PGPASSWORD: password
      PGPORT: 5432
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  finance-analyzer-auth-microservice:
    build: ./finance-analyzer-auth-microservice
    ports:
      - "3000:3000"
    depends_on:
      - finance-analyzer-users-microservice
    networks:
      - app-network

  finance-analyzer-api-getway:
    build: ./finance-analyzer-api-getway
    ports:
      - "5000:5000"
    depends_on:
      - finance-analyzer-auth-microservice
      - finance-analyzer-users-microservice
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  notification-service:
    build: ./finance-analyzer-notification-microservice
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
